# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/posts.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/posts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/posts.proto\x12\x08posts.v1\"\x1c\n\x0eGetPostRequest\x12\n\n\x02id\x18\x01 \x01(\t\"Z\n\x04Post\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\t\x12\x12\n\nupdated_at\x18\x05 \x01(\t\"/\n\x0fGetPostResponse\x12\x1c\n\x04post\x18\x01 \x01(\x0b\x32\x0e.posts.v1.Post\"\x11\n\x0fGetPostsRequest\"<\n\x10GetPostsResponse\x12(\n\x05posts\x18\x01 \x03(\x0b\x32\x19.posts.v1.GetPostResponse2\x8e\x01\n\x05Posts\x12@\n\x07GetPost\x12\x18.posts.v1.GetPostRequest\x1a\x19.posts.v1.GetPostResponse\"\x00\x12\x43\n\x08GetPosts\x12\x19.posts.v1.GetPostsRequest\x1a\x1a.posts.v1.GetPostsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.posts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPOSTREQUEST']._serialized_start=31
  _globals['_GETPOSTREQUEST']._serialized_end=59
  _globals['_POST']._serialized_start=61
  _globals['_POST']._serialized_end=151
  _globals['_GETPOSTRESPONSE']._serialized_start=153
  _globals['_GETPOSTRESPONSE']._serialized_end=200
  _globals['_GETPOSTSREQUEST']._serialized_start=202
  _globals['_GETPOSTSREQUEST']._serialized_end=219
  _globals['_GETPOSTSRESPONSE']._serialized_start=221
  _globals['_GETPOSTSRESPONSE']._serialized_end=281
  _globals['_POSTS']._serialized_start=284
  _globals['_POSTS']._serialized_end=426
# @@protoc_insertion_point(module_scope)
