services:
  development:
    container_name: posts-grpc
    volumes:
      - .:/app
      - /app/.venv
    build:
      context: .
      dockerfile: Dockerfile
      target: development  # Changed from production to development
    command: ["pymon", "--watch", "src/**/*.py", "src/server.py"]
    ports:
      - "50051:50051"
    environment:
      MONGO_USER: root
      MONGO_PASSWORD: example
      MONGO_HOST: db
      MONGO_PORT: 27017
      PORT: 50051
    depends_on:
      - db
      - grpcui
    tty: true
    stdin_open: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - blog_network
  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - db-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example 
    networks:
      - blog_network
  grpcui:
    image: fullstorydev/grpcui:latest
    ports:
      - "8081:8081"
    command: -bind=0.0.0.0 -port=8081 -connect-fail-fast=false -plaintext posts-grpc:50051
    networks:
      - blog_network
volumes:
  db-data:

networks:
  blog_network:
    name: blog_network