# Build development container
build:
    docker compose build development

# Run posts service containers
up: build
    docker compose up -d

# Stop posts service containers
down:
    docker compose down

# Output logs from all containers
logs:
    docker compose logs -f

# Output logs from server container
logs-server:
    docker compose logs -f development

# Check linting errors
check: build
    docker run --rm posts-grpc-development ruff check .
    docker run --rm posts-grpc-development ruff format . --check

# Fix linting errors
fix: build
    docker run --rm posts-grpc-development ruff check --fix
    docker run --rm posts-grpc-development ruff format .

# Run tests
test: build
    docker run --rm posts-grpc-development pytest --cov=src --cov-report=xml:coverage.xml

# Generate proto client
proto: build
    docker run --rm -v $(pwd)/../proto:/proto -v $(pwd):/app posts-grpc-development python -m grpc_tools.protoc -Isrc/proto=/proto/posts/v1 --python_out=/app --pyi_out=/app --grpc_python_out=/app /proto/posts/v1/posts.proto