services:
  development:
    build: 
      context: ./
      dockerfile: Dockerfile
      target: development
    environment:
      - POSTS_API_URL=http://posts-grpc:50051
    ports:
      - "5173:5173"
      - "3000:3000"
    volumes:
      - ./:/frontend
      - node_modules:/frontend/node_modules
    networks:
      - posts-grpc_default
volumes:
  node_modules:

networks:
  posts-grpc_default:
    external: true
