# Build the development container
build:
	docker compose down -v
	docker compose build development

# Start the development container
up: build
	docker compose up -d development

# Stop the development container
down:
	docker compose down development -v

# Test the application
test:
	docker compose run --rm development npm test

# Show the logs of the development container
logs:
	docker compose logs -f development

# Lint the code
lint:
	docker compose run --rm development npm run lint

# Format the code
format:
	docker compose run --rm development npm run format

# Generate proto client
proto:
	docker compose run --rm -v $(pwd)/../proto:/proto development sh -c "mkdir -p /frontend/src/proto && ./node_modules/.bin/grpc_tools_node_protoc --plugin=protoc-gen-ts_proto=./node_modules/.bin/protoc-gen-ts_proto --ts_proto_out=/frontend/src/proto --ts_proto_opt=outputServices=nice-grpc,outputServices=generic-definitions,useExactTypes=false --proto_path=/proto/posts/v1 /proto/posts/v1/posts.proto"