build:
	docker compose down -v
	docker compose build development
	
test:
	echo "unimplemented"
	
up:
	docker compose up -d development

down:
	docker compose down development -v

logs:
	docker compose logs -f development

lint:
	docker compose run --rm development npm run lint

format:
	docker compose run --rm development npm run format


# Generate proto client
proto:
	docker compose run --rm -v $(pwd)/../proto:/proto development sh -c "mkdir -p /frontend/src/proto && ./node_modules/.bin/grpc_tools_node_protoc --plugin=protoc-gen-ts_proto=./node_modules/.bin/protoc-gen-ts_proto --ts_proto_out=/frontend/src/proto --ts_proto_opt=outputServices=nice-grpc,outputServices=generic-definitions,useExactTypes=false --proto_path=/proto/posts/v1 /proto/posts/v1/posts.proto"