build:
	docker compose build development
	
test:
	echo "unimplemented"
	
up:
	docker compose up -d development

down:
	docker compose down development -v

logs:
	docker compose logs -f development

lint:
	docker compose run --rm development npm run lint

format:
	docker compose run --rm development npm run format

