/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PostIdImport } from './routes/post/$id'
import { Route as PostIdEditImport } from './routes/post/$id.edit'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PostIdRoute = PostIdImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => rootRoute,
} as any)

const PostIdEditRoute = PostIdEditImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PostIdRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/post/$id': {
      id: '/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof PostIdImport
      parentRoute: typeof rootRoute
    }
    '/post/$id/edit': {
      id: '/post/$id/edit'
      path: '/edit'
      fullPath: '/post/$id/edit'
      preLoaderRoute: typeof PostIdEditImport
      parentRoute: typeof PostIdImport
    }
  }
}

// Create and export the route tree

interface PostIdRouteChildren {
  PostIdEditRoute: typeof PostIdEditRoute
}

const PostIdRouteChildren: PostIdRouteChildren = {
  PostIdEditRoute: PostIdEditRoute,
}

const PostIdRouteWithChildren =
  PostIdRoute._addFileChildren(PostIdRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/post/$id': typeof PostIdRouteWithChildren
  '/post/$id/edit': typeof PostIdEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/post/$id': typeof PostIdRouteWithChildren
  '/post/$id/edit': typeof PostIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/post/$id': typeof PostIdRouteWithChildren
  '/post/$id/edit': typeof PostIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/post/$id' | '/post/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/post/$id' | '/post/$id/edit'
  id: '__root__' | '/' | '/post/$id' | '/post/$id/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostIdRoute: typeof PostIdRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostIdRoute: PostIdRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/post/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/post/$id": {
      "filePath": "post/$id.tsx",
      "children": [
        "/post/$id/edit"
      ]
    },
    "/post/$id/edit": {
      "filePath": "post/$id.edit.tsx",
      "parent": "/post/$id"
    }
  }
}
ROUTE_MANIFEST_END */
