services:
  devcontainer:
    build: 
      context: ../../posts
      dockerfile: Dockerfile
      target: development
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
networks:
  default:
    name: posts-dev-network
volumes:
  mongodb-data: 