name: Posts Service Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'posts/**'
      - 'docker-compose.yaml'
      - '.github/workflows/posts-test.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'posts/**'
      - 'docker-compose.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Run posts tests
      run: docker-compose run --rm posts-test 