name: Posts CI

on:
  push:
    paths:
      - 'posts/**'
      - '.github/workflows/posts.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Run posts tests
      run: |
        cd posts
        make lint
        make test