name: Posts CI

on:
  push:
    paths:
      - 'posts-grpc/**'
      - 'proto/posts/**'
      - '.github/workflows/posts-grpc.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    
    steps:
    - name: Set up Just
      uses: extractions/setup-just@v3

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build image
      run: |
        cd posts-grpc
        just build

    - name: Generate proto
      run: |
        cd posts-grpc
        just proto

    - name: Ruff checks
      run: |
        cd posts-grpc
        just check

    - name: Test
      run: |
        cd posts-grpc
        just test

    - name: Get Cover 
      uses: orgoro/coverage@v3.2
      with:
        coverageFile: posts-grpc/coverage.xml
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    
    - name: Extract metadata (tags, labels)
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=ref,event=branch
          type=ref,event=tag
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha,format=short    # <-- commit hash tag (e.g. :abc1234)
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        target: production
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}