name: Buf CI
on:
  push:
    paths:
    - 'proto/**'
    - '.github/workflows/proto.yaml'
permissions:
  contents: read
  pull-requests: write
jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          format: true
          lint: true
          breaking: true
          breaking-against: '.git#branch=main,ref=HEAD~1,subdir=proto'
          push: false
